init commit for tdnn passes
xmos/ai_tools pull request #400
Opened 2021-02-22 17:22 UTC by scott-xmos

Work from before tensorflow made their streaming plans public

2021-08-31 13:34 UTC, panickal-xmos commented on tflite2xcore/tflite2xcore/converter.py
> +    # if external_memory:
Why are we commenting this out?

2021-08-31 13:37 UTC, panickal-xmos commented on tflite2xcore/tflite2xcore/converter.py
> +        self.register_pass(passes.PersistentBufferSize())
Could we please follow the same naming convention for passes? 
So `PersistentBufferSize` would probably be something like `TdnnPersistentBufferSizePass`. Similarly `TdnnCleanup` would be `TdnnCleanupPass`

2021-08-31 14:35 UTC, scott-xmos commented on tflite2xcore/tflite2xcore/converter.py
> +    # if external_memory:
The tests were failing because of the external_memory option, but it seems to be fixed now.

2021-09-01 08:42 UTC, panickal-xmos commented on tflite2xcore/tflite2xcore/transformation_passes/pooling_passes.py
> +        return new_op
Was this a bug? Good catch!

2021-09-01 09:49 UTC, andrewstanfordjason commented on tflite2xcore/tflite2xcore/converter.py
> +    pass_mgr.register_passes(ParametricOperatorLoweringManager())
Why has this been added? is ti because the tdnn needs it or some other reason?

2021-09-01 10:32 UTC, andrewstanfordjason requested changes
looks really good. spotted a couple of things.

2021-09-01 10:32 UTC, andrewstanfordjason commented on tflite2xcore/tflite2xcore/transformation_passes/tdnn_passes.py
> +        new_op = insert_ringbuffer(ringbuffer_time_dim, op)
should new_op be returned?

2021-09-01 21:24 UTC, scott-xmos commented on tflite2xcore/tflite2xcore/transformation_passes/pooling_passes.py
> +        return new_op
An earlier version of the TDNN converter needed the new_op to be returned. Probably good to have for consistency.

2021-09-01 22:25 UTC, scott-xmos commented on tflite2xcore/tflite2xcore/converter.py
> +    pass_mgr.register_passes(ParametricOperatorLoweringManager())
Good catch. It was a mistake from all the rebasing I was doing. One of the reasons I want to merge the TDNN branch.

2021-09-02 21:01 UTC, scott-xmos commented on tflite2xcore/tflite2xcore/transformation_passes/tdnn_passes.py
> +        new_op = insert_ringbuffer(ringbuffer_time_dim, op)
The new_op / op definitions got messed over time. I cleaned them up.

2021-09-09 15:24 UTC, andrewstanfordjason approved these changes

2021-09-09 15:38 UTC, panickal-xmos approved these changes
+1 , happy for the PR to be merged when the CI passes.

2023-04-04 21:11 UTC, closed without merging