Profiling precision
xmos/ai_tools pull request #544
Opened 2022-02-01 15:04 UTC by aranXmos

2022-02-01 15:11 UTC, andrewstanfordjason requested changes
Should all the pngs be checked in? I understand the test images but the others seem like they should be generated on demand by a script

2022-02-01 15:22 UTC, aranXmos commented
Probably not, just removed the artefacts for building the report (leaving the report.html)
@andrewstanfordjason

2022-02-01 16:52 UTC, andrewstanfordjason commented on tools/precision profiling/model_splitting.py
> +if len(sys.argv) == 1:
in the future using argparse would make your life easier.

2022-02-01 17:08 UTC, andrewstanfordjason requested changes
we might want to have the 
 tools/precision profiling/schema.fbs
reference the third_party repo as the schema is there and will be always up-to-date

2022-02-01 17:08 UTC, andrewstanfordjason commented on tools/precision profiling/ms_lib.py
> +import cv2
I would favour using the tf function over cv2 as cv2 could be subtly incompatible and would mean inputting fewer dependencies.

2022-02-01 17:08 UTC, andrewstanfordjason commented on tools/precision profiling/ms_lib.py
> +def hists(histogram, layer, hist_type, opList):
as a general rule try to keep each function to a single responsibility, i.e. draw the histogram to a plot and another to save a plot to a file in a dir. That way its much easier to change global behaviour rather than search for everywhere you wrote out files/etc.

2022-02-02 09:30 UTC, aranXmos commented
> we might want to have the
> tools/precision profiling/schema.fbs
> reference the third_party repo as the schema is there and will be always up-to-date

For this point, I can't find the schema in ai_tools/third_party? I don't think it exists there

2022-02-02 09:49 UTC, andrewstanfordjason commented on tools/precision profiling/ms_lib.py
> +def hists(histogram, layer, hist_type, opList):
it should be at
ai_tools/third_party/tensorflow/tensorflow/lite/schema/schema.fbs

2022-02-02 09:52 UTC, andrewstanfordjason commented on tools/precision profiling/ms_lib.py
> +def hists(histogram, layer, hist_type, opList):
sorry, tf is not a submodule, ignore this

2022-02-02 10:49 UTC, closed without merging